parameters:
    jb_fileuploader.resolver.assets.class: Jb\Bundle\FileUploaderBundle\Service\Resolver\AssetsResolver
    jb_fileuploader.resolver_chain.class: Jb\Bundle\FileUploaderBundle\Service\ResolverChain
    jb_fileuploader.resolver.imagine.class: Jb\Bundle\FileUploaderBundle\Service\Resolver\ImagineCacheManagerResolver

services:
    jb_fileuploader.resolver_chain:
        class: "%jb_fileuploader.resolver_chain.class%"
        scope: request

    jb_fileuploader.resolver.imagine:
        class: %jb_fileuploader.resolver.imagine.class%
        scope: request
        arguments:
            - @liip_imagine.cache.manager
        tags:
            - { name: jb_fileuploader.resolver, alias: imagine }

    jb_fileuploader.resolver.assets:
        class: %jb_fileuploader.resolver.assets.class%
        scope: request
        arguments:
            - @templating.helper.assets
            - %jb_fileuploader.assets_directory%
        tags:
            - { name: jb_fileuploader.resolver, alias: assets }