parameters:
    jb_fileuploader.resolver_factory.asset.class: Jb\Bundle\FileUploaderBundle\DependencyInjection\ResolverFactory\AssetsResolverFactory
    jb_fileuploader.resolver_factory.imagine.class: Jb\Bundle\FileUploaderBundle\DependencyInjection\ResolverFactory\ImagineResolverFactory

services:
    jb_fileuploader.resolver_factory.asset:
        class: "%jb_fileuploader.resolver_factory.asset.class%"
        tags:
            - { name: jb_fileuploader.resolver.factory }

    jb_fileuploader.resolver_factory.imagine:
        class: "%jb_fileuploader.resolver_factory.imagine.class%"
        tags:
            - { name: jb_fileuploader.resolver.factory }